print("Displaying Numeric types \n int \n float \n complex \n bool")
num1 =5
num2 =5.25
num3 =complex(num1,num2)
print("Integer type num1 :")
type(num1)
print(num1)
print("Float type num2 :")
type(num2)
print(num2)
print("Complex type num3 :")
type(num3)
print(num3)
print("Bool type if(num1 >num2)")
type(num1>num2)
print(num1>num2)